import Head from 'next/head'
import Image from 'next/image'
import { BoltIcon, ChartBarIcon, ClockIcon, DevicePhoneMobileIcon, GlobeAltIcon, GlobeAsiaAustraliaIcon, ListBulletIcon, ScaleIcon } from '@heroicons/react/24/outline'
import styles from '../../styles/home.module.css'
import * as medium1 from '../../public/medium1.png'
import React from 'react'
import { sendUsers } from '../api/users'
import UserList from '../../components/UserList'

const features = [
  {
    name: 'Time your work',
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores impedit perferendis suscipit eaque, iste dolor cupiditate blanditiis ratione.',
    icon: ClockIcon,
  },
  {
    name: 'Complete your tasks',
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores impedit perferendis suscipit eaque, iste dolor cupiditate blanditiis ratione.',
    icon: ListBulletIcon,
  },
  {
    name: 'Use it anywhere',
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores impedit perferendis suscipit eaque, iste dolor cupiditate blanditiis ratione.',
    icon: GlobeAsiaAustraliaIcon,
  },
  {
    name: 'View your stats',
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores impedit perferendis suscipit eaque, iste dolor cupiditate blanditiis ratione.',
    icon: ChartBarIcon,
  },
]

//function that gets the users from the api

export default function leaderBoard() {
  return(
    <div className={' bg-neutral-900'}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main+' bg-neutral-900'}>
      <div className="sm:mb-8 sm:flex sm:justify-center">
    <UserList />
    </div>
      </main>

      <footer className={styles.footer+' mt-20'}>
        <a
          href="https://pomohub.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Pomo Hub Footer Placeholder :0
        </a>
      </footer>
    </div>
  )
}
